import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Vulnerability } from '@/types';
import { cleanText } from './utils';

export const generatePDFReport = (vulnerabilities: Vulnerability[], summary: string, fileName: string) => {
  const doc = new jsPDF();
  const date = new Date().toLocaleDateString();

  // Header background
  doc.setFillColor(248, 250, 252);
  doc.rect(0, 0, 210, 40, 'F');

  // Title
  doc.setFontSize(24);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text('ShadowScan', 14, 20);
  
  doc.setFontSize(16);
  doc.setTextColor(71, 85, 105); // slate-600
  doc.text('Security Analysis Report', 14, 30);

  // Info Column
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text(`Project: ${fileName}`, 150, 20);
  doc.text(`Date: ${date}`, 150, 25);
  doc.text(`Findings: ${vulnerabilities.length}`, 150, 30);

  // Horizontal line
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.line(14, 40, 196, 40);

  // Executive Summary Section
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', 14, 52);
  
  doc.setFontSize(10);
  doc.setTextColor(51, 65, 85); // slate-700
  doc.setFont('helvetica', 'normal');
  const cleanedSummary = cleanText(summary);
  const splitSummary = doc.splitTextToSize(cleanedSummary, 182);
  doc.text(splitSummary, 14, 60);

  // Calculate position for next section
  const summaryHeight = splitSummary.length * 5;
  const startVulnY = 60 + summaryHeight + 15;

  // Vulnerability findings header
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.text('Detailed Findings', 14, startVulnY);

  // Vulnerability Table
  const tableData = vulnerabilities.map(v => [
    v.severity.toUpperCase(),
    cleanText(v.name),
    v.fileName,
    v.lineNumber.toString()
  ]);

  autoTable(doc, {
    startY: startVulnY + 5,
    head: [['Severity', 'Vulnerability', 'File', 'Line']],
    body: tableData,
    headStyles: { 
      fillColor: [15, 23, 42], // slate-900
      textColor: [255, 255, 255],
      fontSize: 10,
      fontStyle: 'bold',
      halign: 'left'
    },
    bodyStyles: {
      fontSize: 9,
      textColor: [51, 65, 85]
    },
    alternateRowStyles: { 
      fillColor: [248, 250, 252] 
    },
    columnStyles: {
      0: { cellWidth: 30, fontStyle: 'bold' },
      1: { cellWidth: 'auto' },
      2: { cellWidth: 50 },
      3: { cellWidth: 20, halign: 'center' }
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 0) {
        const severity = data.cell.raw;
        if (severity === 'HIGH') data.cell.styles.textColor = [220, 38, 38]; // red-600
        else if (severity === 'MEDIUM') data.cell.styles.textColor = [217, 119, 6]; // amber-600
        else if (severity === 'LOW') data.cell.styles.textColor = [22, 163, 74]; // green-600
      }
    },
    margin: { top: 20 },
    theme: 'striped'
  });

  // Footer with page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    doc.text(
      'Generated by ShadowScan AI Security',
      14,
      doc.internal.pageSize.getHeight() - 10
    );
  }

  doc.save(`shadowscan-report-${fileName.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}.pdf`);
};
